{
 "title": "Pathfinder Platform Status Page",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CLUSTER SERVICES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://kubernetes.default.svc.cluster.local\",job=\"blackbox_no_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "OpenShift Cluster API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://console.lab.pathfinder.gov.bc.ca:8443\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "Metrics API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://hawkular-metrics.lab.pathfinder.gov.bc.ca\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "Lab Content",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://labs-devops-platform-workshops.lab.pathfinder.gov.bc.ca\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  { "title": "INTERNAL CLUSTER SERVICES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GitHub Connectivity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://github.com/bcdevops/platform-services\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "Fail Test",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://failme.lab.pathfinder.gov.bc.ca\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "Red Hat Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://access.redhat.com/containers/\",job=\"blackbox_tls_verify\"}\t"
    }
   ]
  },
  {
   "title": "DNS Resolution Time(s)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(probe_dns_lookup_time_seconds)"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "NOTICES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Notices",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "content": "---\n\n# Notice: 05-31-19-1915.md \n\n## Welcome to DevOpsDays\nThis is a broadcast message!! \n\n---\n\n# Notice: 05-30-19-1700.md \n\n## This is a system test. \n\n---\n\n# Notice: 05-30-19-1456.md \n\n## QA complete - this concludes OS patching for all Openshift systems for this quarter. \n\n---\n\n# Notice: 05-29-19-2330.md \n\n## Just wanting to advise everyone that it's a beautiful day and walking around outside is quite beneficial. \n\n---\n\n# Notice: 05-28-19-1123.md \n\n##  Impactful work regarding server reboots is now finished for the OS patching of the OpenShift cluster. Final QA tests progressing - those will not be impactful. \n\n---\n\n# Notice: 05-28-19-0848.md \n\n## RFC179441 - 2019 Q2 OS patching for PROD cluster/NFS server. Work on this concludes today (starting at 9:00am PDT) with the patching of the last storage node - no impact to storage availability and provisioning new volumes. Will announce when all work and checks are finished. \n\n",
   "targets": [
    {}
   ]
  }
 ]
}